export EDITOR="code --wait"
export GOBIN=$HOME/workspace/go/bin
export GOPATH=$HOME/workspace/go
export PATH=$HOME/bin:/usr/local/bin:$PATH
export VISUAL="/usr/bin/vim"

alias c="clear"
alias edit="nano ~/.zshrc"
alias g="git"
alias ga="g add -A"
alias gc="g commit -m"
alias gac="ga && gc"
alias gr="g reset --hard"
alias gp="g pull"
alias gs="g status"
alias gbd="g branch -D"
alias work="cd ~/workspace"
alias python='python3'
alias edit="nano ~/.bash_profile"